# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vince_animal_game', '0002_auto_20160227_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('REGION', 'Region'), ('LANGUAGE', 'Language'), ('POPULATION', 'Population'), ('LANDLOCKED', 'Landlocked'), ('GDP', 'GDP')], max_length=120)),
                ('precision', models.CharField(max_length=120)),
            ],
        ),
    ]
