# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vince_animal_game', '0003_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('REGION', 'Region'), ('LANGUAGE', 'Language'), ('POPULATION', 'Population'), ('AREA', 'Area'), ('LANDLOCKED', 'Landlocked'), ('GDP', 'GDP')], max_length=120),
        ),
    ]
