# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vince_animal_game', '0004_auto_20160227_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
