# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vince_animal_game', '0006_auto_20160227_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answered',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='precision',
            new_name='query_field',
        ),
    ]
