# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vince_animal_game', '0007_auto_20160227_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
