# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoSerializer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protoSerializer.proto',
  package='protoData.animals',
  serialized_pb=_b('\n\x15protoSerializer.proto\x12\x11protoData.animals\")\n\x05query\x12\x10\n\x08question\x18\x01 \x02(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x02(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUERY = _descriptor.Descriptor(
  name='query',
  full_name='protoData.animals.query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='protoData.animals.query.question', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answer', full_name='protoData.animals.query.answer', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['query'] = _QUERY

query = _reflection.GeneratedProtocolMessageType('query', (_message.Message,), dict(
  DESCRIPTOR = _QUERY,
  __module__ = 'protoSerializer_pb2'
  # @@protoc_insertion_point(class_scope:protoData.animals.query)
  ))
_sym_db.RegisterMessage(query)


# @@protoc_insertion_point(module_scope)
