application: backend 
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on

#url: /_ah/(mapreduce|queue|warmup).*
#  script: animalgame.wsgi.application
#  login: admin

#url: /.*
#  script: animalgame.wsgi.application
