# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: json.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='json.proto',
  package='Game.Cars',
  serialized_pb=_b('\n\njson.proto\x12\tGame.Cars\"\xdd\x02\n\x03\x43\x61r\x12\r\n\x05model\x18\x01 \x02(\t\x12%\n\x06vendor\x18\x02 \x02(\x0b\x32\x15.Game.Cars.Car.Vendor\x12)\n\x05speed\x18\x03 \x01(\x0e\x32\x14.Game.Cars.Car.Speed:\x04\x46\x41ST\x1ar\n\x06Vendor\x12\x0c\n\x04name\x18\x01 \x02(\t\x12.\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x1d.Game.Cars.Car.Vendor.Address\x12\x0e\n\x06models\x18\x03 \x03(\t\x1a\x1a\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x63ountry\x18\x01 \x02(\t\x1a_\n\x06Holder\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x02(\t\x12.\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x1d.Game.Cars.Car.Vendor.Address\" \n\x05Speed\x12\x08\n\x04\x46\x41ST\x10\x01\x12\r\n\tSUPERFAST\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CAR_SPEED = _descriptor.EnumDescriptor(
  name='Speed',
  full_name='Game.Cars.Car.Speed',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FAST', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUPERFAST', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=343,
  serialized_end=375,
)
_sym_db.RegisterEnumDescriptor(_CAR_SPEED)


_CAR_VENDOR_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='Game.Cars.Car.Vendor.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='Game.Cars.Car.Vendor.Address.country', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=244,
)

_CAR_VENDOR = _descriptor.Descriptor(
  name='Vendor',
  full_name='Game.Cars.Car.Vendor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Game.Cars.Car.Vendor.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='Game.Cars.Car.Vendor.address', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='models', full_name='Game.Cars.Car.Vendor.models', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CAR_VENDOR_ADDRESS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=244,
)

_CAR_HOLDER = _descriptor.Descriptor(
  name='Holder',
  full_name='Game.Cars.Car.Holder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='Game.Cars.Car.Holder.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='Game.Cars.Car.Holder.last_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='Game.Cars.Car.Holder.address', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=341,
)

_CAR = _descriptor.Descriptor(
  name='Car',
  full_name='Game.Cars.Car',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='Game.Cars.Car.model', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vendor', full_name='Game.Cars.Car.vendor', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='Game.Cars.Car.speed', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CAR_VENDOR, _CAR_HOLDER, ],
  enum_types=[
    _CAR_SPEED,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=375,
)

_CAR_VENDOR_ADDRESS.containing_type = _CAR_VENDOR
_CAR_VENDOR.fields_by_name['address'].message_type = _CAR_VENDOR_ADDRESS
_CAR_VENDOR.containing_type = _CAR
_CAR_HOLDER.fields_by_name['address'].message_type = _CAR_VENDOR_ADDRESS
_CAR_HOLDER.containing_type = _CAR
_CAR.fields_by_name['vendor'].message_type = _CAR_VENDOR
_CAR.fields_by_name['speed'].enum_type = _CAR_SPEED
_CAR_SPEED.containing_type = _CAR
DESCRIPTOR.message_types_by_name['Car'] = _CAR

Car = _reflection.GeneratedProtocolMessageType('Car', (_message.Message,), dict(

  Vendor = _reflection.GeneratedProtocolMessageType('Vendor', (_message.Message,), dict(

    Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
      DESCRIPTOR = _CAR_VENDOR_ADDRESS,
      __module__ = 'json_pb2'
      # @@protoc_insertion_point(class_scope:Game.Cars.Car.Vendor.Address)
      ))
    ,
    DESCRIPTOR = _CAR_VENDOR,
    __module__ = 'json_pb2'
    # @@protoc_insertion_point(class_scope:Game.Cars.Car.Vendor)
    ))
  ,

  Holder = _reflection.GeneratedProtocolMessageType('Holder', (_message.Message,), dict(
    DESCRIPTOR = _CAR_HOLDER,
    __module__ = 'json_pb2'
    # @@protoc_insertion_point(class_scope:Game.Cars.Car.Holder)
    ))
  ,
  DESCRIPTOR = _CAR,
  __module__ = 'json_pb2'
  # @@protoc_insertion_point(class_scope:Game.Cars.Car)
  ))
_sym_db.RegisterMessage(Car)
_sym_db.RegisterMessage(Car.Vendor)
_sym_db.RegisterMessage(Car.Vendor.Address)
_sym_db.RegisterMessage(Car.Holder)


# @@protoc_insertion_point(module_scope)
